name: automated-testing-load

on:
  push:
    branches: ["staging", "feature/**" ]
  workflow_dispatch:

jobs:
  merge-delete-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge any -> staging
        if: startsWith(github.ref, 'refs/heads/feature/')  # Check if the branch is a feature branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete merged feature branch
        if: startsWith(github.ref, 'refs/heads/feature/')  # Check if the branch is a feature branch
        run: |
          git push origin --delete ${{ github.ref }}
        
      # Optional: Clean up tags if required
      - name: Clean up local tags
        run: |
          git fetch --tags
